# Maps of locations

LOCATION1_MAP = [
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'h  x  x     x        x     x  x',
    'x  x  x  xxxxxxx  xxxx  x  x  x',
    'x     x  x              x     x',
    'x  x  x  x  x  xxxxxxxxxx  xxxx',
    'x  x     x  x  x        x     x',
    'x  xxxxxxxxxxxxx  x  x  xxxx  x',
    'x        x        x  x  x     x',
    'xxxxxxx  x  x  x  xxxxxxxxxx  x',
    'x     x     x  x              x',
    'x  xxxxxxxxxx  xxxxxxxxxx  x  x',
    'x     x  x              x  x  x',
    'xxxx  x  x  xxxxxxxxxx  xxxxxxx',
    'x              x           x  x',
    'xxxx  x  x  xxxxxxx  xxxxxxx  x',
    'x     x  x  x  x           x  x',
    'x  xxxxxxx  x  xxxxxxx  xxxx  x',
    'x  x        x  x     x        x',
    'x  x  xxxxxxx  x  x  xxxx  xxxx',
    'x  x              x  x         ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 
]
